server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url :
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: order-service
          uri: lb://ORDER
          predicates:
            - Path=/order-service, /order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
            - RewritePath=/order-service, /
        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<path>.*), /$\{path}
            
            
  