server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url :
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**
        