version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
  kafka:
    #windows docker-compose error fix : https://github.com/wurstmeister/kafka-docker/issues/529
    #build: .
    image: wurstmeister/kafka
    ports:
      #https://github.com/wurstmeister/kafka-docker/issues/211 could not be established. Broker may not be available 해당 오류로 인해 변경처리(외부에서 dokcer 9092포트로 접근이 안됨 9092를 외부에서 열어줌)
      #- "9092"
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      #linux option
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      #windows option
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped